#define CLEAR           "clear"
#define CREATE_RC       "create-rc"
#define TITLE           "title"
#define HLINE           "hline"
#define HFILE           "hfile"
#define YESNO           "yesno"
#define MSGBOX          "msgbox"
#define INFOBOX         "infobox"
#define INPUTBOX        "inputbox"
#define TEXTBOX         "textbox"
#define MENU            "menu"
#define PRGBOX          "prgbox"
#define CHECKLIST       "checklist"
#define RADIOLIST       "radiolist"
#define FTREE           "ftree"
#define TREE            "tree"

#define CLEAR_OPT       1
#define CREATE_RC_OPT   2
#define TITLE_OPT       3
#define HLINE_OPT       4
#define HFILE_OPT       5
#define YESNO_OPT       6
#define MSGBOX_OPT      7
#define INFOBOX_OPT     8
#define INPUTBOX_OPT    9
#define TEXTBOX_OPT     10
#define MENU_OPT        11
#define PRGBOX_OPT      12
#define CHECKLIST_OPT   13
#define RADIOLIST_OPT   14
#define FTREE_OPT       15
#define TREE_OPT        16
